### PR TITLE
Updated unincorportated controllers to get and put data to mongodb

### PR DESCRIPTION
**Pull request by ttingle-ch**
Updated unit tests to mock get from db
moved unincorporated tests to an unincorporated folder

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by abhiahirv1 — APPROVED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hemerem-ch — APPROVED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by abhiahirv1 — APPROVED** [review]
LGTM

**Review by sardhani-ch — APPROVED** [review]
LGTM

**Pull request merged**
