### PR TITLE
Idva5 1133 what is your email address

### PR DESCRIPTION
**Pull request by ttingle-ch**
Added screens to collect users correspondence email address for all journeys

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hemerem-ch — APPROVED** [review]
LGTM

**Review by sardhani-ch — APPROVED** [review]
LGTM

**Review by cbroadley-ch — APPROVED** [review]
LGTM

**Pull request merged**
