### PR TITLE
Error handling fix

### PR DESCRIPTION
**Pull request by ttingle-ch**
- Updated all controllers to handle errors

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by swalke-ch — DISMISSED** [review]

**Review by hemerem-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hemerem-ch — APPROVED** [review]

**Review by swalke-ch — APPROVED** [review]

**Pull request merged**
