### PR TITLE
Adding undefined check for correspondence address.

### PR DESCRIPTION
**Pull request by sampankumar**
Adding undefined check for correspondence address.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cbroadley-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by ttingle-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by ttingle-ch — APPROVED** [review]

**Review by hemerem-ch — APPROVED** [review]

**Pull request merged**
