### PR TITLE
IDVA5-554-required-change

### PR DESCRIPTION
**Pull request by abhiahirv1**
[Sole trader] Routing for What is your role?

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cconnor-ch — APPROVED** [review]

**Review by atedros-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by sampankumar — APPROVED** [review]

**Pull request merged**
