### PR TITLE
Idva5-448 what is the business name sole trader

### PR DESCRIPTION
**Pull request by atedros-ch**
- what is the business name page created for sole trader

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hemerem-ch — DISMISSED** [review]
LGTM

**Review by abhiahirv1 — DISMISSED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by abhiahirv1 — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by swalke-ch — APPROVED** [review]

**Review by hemerem-ch — APPROVED** [review]

**Pull request merged**
