### PR TITLE
IDVA5-1483 Add new navbar to Registration/Update ACSP screens

### PR DESCRIPTION
**Pull request by rnesbitt-ch**
https://companieshouse.atlassian.net/browse/IDVA5-1483 - Update ACSP
https://companieshouse.atlassian.net/browse/IDVA5-1605 - Registration

Added the new navbar component across both Registration and Update ACSP. There is a conditional check for 'userEmail' so the navbar will not show until the user is logged into the Registration service. For Update ACSP they are redirected to log in before accessing the start page.

'Authorised agent' link should not be visible for anyone not part of an ACSP so this value is being set based on acspNumber and then dynamically showing/hiding it on navbar.

**Registration - not logged in**
image

**Registration - logged in**
image

**Update ACSP - logged in**
image

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by sampankumar — APPROVED** [review]

**Review by rdas-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by swalke-ch — APPROVED** [review]

**Review by sardhani-ch — APPROVED** [review]

**Review by sampankumar — APPROVED** [review]

**Review by ttingle-ch — COMMENTED** [review]
Should the Approved agent link not be shown on the registration journey as they are not currently approved agents and should not be able to see that dashboard

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by ttingle-ch — APPROVED** [review]
LGTM

**Review by atedros-ch — APPROVED** [review]

**Pull request merged**
