### PR TITLE
Idva5 1185 matomo analytics updates

### PR DESCRIPTION
**Pull request by ttingle-ch**
Removed duplicate urls showing in Matomo
Updated analytics for unincorporated and sole trader journeys
Linting fixes
Added missing Welsh translations for what is your role.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cbroadley-ch — APPROVED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cbroadley-ch — DISMISSED** [review]

**Review by cbroadley-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cbroadley-ch — APPROVED** [review]

**Review by abhiahirv1 — APPROVED** [review]

**Pull request merged**
