### PR TITLE
IDVA6-177-required-changes

### PR DESCRIPTION
**Pull request by abhiahirv1**
Calling businessName from ACSPData model

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hemerem-ch — APPROVED** [review]

**Review by atedros-ch — APPROVED** [review]
LGTM

**Pull request merged**
