### PR TITLE
IDVA5-1373 Updating correspondence address to allow international addresses

### PR DESCRIPTION
**Pull request by ttingle-ch**
- Updated the correspondence address auto lookup hit text to inform the user they must use manual address entry if their address is outside of the UK
- Updated the correspondence address manual entry screen to use the typeahead input for selecting the country
- Updated the validation on the postcode to validate UK postcodes if the country entered is within the UK and if not validates no special characters and 15 chars or less

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by cbroadley-ch — APPROVED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by sampankumar — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by cbroadley-ch — APPROVED** [review]
LGTM

**Pull request merged**
