### PR TITLE
Started new transaction when user changes type of business

### PR DESCRIPTION
**Pull request by ttingle-ch**
- Started new transaction when user changes type of business
- Deleted old transaction and application when the user changes type of business
- Moved the creation of the transaction to post

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by swalke-ch — APPROVED** [review]

**Review by cbroadley-ch — APPROVED** [review]

**Pull request merged**
