### PR TITLE
Idva5-586-radio buttons don't go to correct page

### PR DESCRIPTION
**Pull request by atedros-ch**
- radio button redirect fix for what type of business are you registering page

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by abhiahirv1 — DISMISSED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by sampankumar — APPROVED** [review]

**Pull request merged**
