### PR TITLE
Updated idva5 820 aml save and continue

### PR DESCRIPTION
**Pull request by sampankumar**
Updated idva5 820 aml save and continue

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hemerem-ch — DISMISSED** [review]

**Review by sardhani-ch — APPROVED** [review]
LGTM

**Review by ttingle-ch — APPROVED** [review]
LGTM

**Review by hemerem-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
