### PR TITLE
IDVA5-762-saved-application

### PR DESCRIPTION
**Pull request by abhiahirv1**
Initial commit

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by sardhani-ch — APPROVED** [review]
LGTM

**Review by hemerem-ch — APPROVED** [review]

**Pull request merged**
